### Welcome to the API! 🚀
GET http://localhost:3000/api
Content-Type: application/json

### Greeting
POST http://localhost:3000/api?message=hello
Content-Type: application/json

{
  "fullName": "Eru Dev"
}

### Error API Example
GET http://localhost:3000/api/error
Content-Type: application/json